<?php

class Cylinder1 extends Circle1
{
    public $height;
    public function __construct($radius, $color,$height)
    {
        parent::__construct($radius, $color);
        $this->height=$height;
    }
    public function surroundingArea(){
        return parent::circleArea()*$this->height;
    }
    public function totalArea(){
        return parent::circlePerimeter()*2+parent::circleArea()*$this->height;
    }
    public function getColor()
    {
        return parent::getColor(); // TODO: Change the autogenerated stub
    }
}